server:
  port: 9001
spring:
  application:
    name: codecommunity-base
  jpa:
    database: mysql
    show-sql: true

#数据库连接在application.properties配置了，未上传
#spring
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url:
#    username:
#    password: