server:
  port: 9002
spring:
  application:
    name: codecommunity-recruit
  jpa:
    database: mysql
    show-sql: true

#数据库连接在application.properties配置了
#spring
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url:
#    username:
#    password: